apiVersion: apps/v1
kind: Deployment
metadata:
  name: internproject-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internproject-backend
  template:
    metadata:
      labels:
        app: internproject-backend
    spec:
      containers:
      - name: backend
        image: danialumer876/backend:latest
        ports:
        - containerPort: 5100
        env:
        - name: NAME
          value: "Danial"

