apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: danialumer876/backend:latest
        ports:
        - containerPort: 5100
        env:
        - name: NAME
          value: "Danial"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: danialumer876/frontend:latest
        ports:
        - containerPort: 5200
        env:
        - name: frontend-server
          valueFrom:
            configMapKeyRef:
              name: intern-project-config
              key: backend-url
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5100
    targetPort: 5100
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 5200
    targetPort: 5200
    nodePort: 30006
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: intern-project-config
data:
  backend-url: backend-service
