apiVersion: v1
kind: Service
metadata:
  name: internproject-frontend
spec:
  type: NodePort
  selector:
    app: internproject-frontend
  ports:
  - protocol: TCP
    port: 5200
    targetPort: 5200
    nodePort: 30006
